version: '2'
services:
  backend:
    build: 
    context: employee_admin
    args:
      PROJECT_NAME: employee_admin
      PROJECT_VERSION: 1.0-SNAPSHOT
    networks:
      - backend
      - frontend
    depends_on:
      - "redis"
    environment:
      - TEXT_PREFIX=hello
  frontend:
    build: frontend
    ports:
      - "8099:80"
    networks:
      - frontend
    volumes:
       - ./frontend/app:/app
    depends_on:
      - "backend"
  redis:
    image: redis:alpine
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
