version: '2'
services:
  employee_admin:
    build: 
      context: employee_admin
      args:
        PROJECT_NAME: employee_admin
        PROJECT_VERSION: 1.0-SNAPSHOT
    networks:
      - backend
      - frontend
    depends_on:
      - "redis"
    environment:
      - MYSQL_HOST=123.123.123
  frontend:
    build: frontend
    ports:
      - "8099:80"
    networks:
      - frontend
    volumes:
       - ./frontend/app:/app
    depends_on:
      - "employee_admin"
    environment:
      - TEXT_PREFIX=Prefisso
      - BACKEND_HOST=employee_admin
  redis:
    image: redis:alpine
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
